"use client";

import { Button } from "@/components/ui/button";
import { formatPkr } from "@/lib/utils";
import { Printer } from "lucide-react";

export type PrintLine = {
  product_code: string;
  product_name: string;
  qty: number;
  rate?: number;
  discount?: number;
  amount?: number;
};

export function PrintDocument({
  companyName,
  companyAddress,
  title,
  docNo,
  date,
  partyName,
  partyCode,
  warehouseName,
  extraMeta,
  lines,
  totals,
}: {
  companyName: string;
  companyAddress?: string | null;
  title: string;
  docNo: string;
  date: string;
  partyName?: string;
  partyCode?: string;
  warehouseName?: string;
  extraMeta?: { label: string; value: string }[];
  lines: PrintLine[];
  totals?: { label: string; value: string }[];
}) {
  return (
    <div className="space-y-4">
      <div className="no-print flex justify-end gap-2">
        <Button type="button" onClick={() => window.print()}>
          <Printer className="h-4 w-4" />
          Print
        </Button>
      </div>

      <div className="print-sheet panel mx-auto max-w-3xl p-8">
        <div className="border-b border-[var(--border)] pb-4">
          <h1 className="font-[family-name:var(--font-display)] text-2xl font-semibold">
            {companyName}
          </h1>
          {companyAddress ? (
            <p className="mt-1 text-sm text-[var(--muted)]">{companyAddress}</p>
          ) : null}
          <p className="mt-3 text-xs font-semibold uppercase tracking-[0.16em] text-[var(--brand)]">
            {title}
          </p>
        </div>

        <div className="mt-4 grid gap-2 text-sm sm:grid-cols-2">
          <p>
            <span className="text-[var(--muted)]">No:</span>{" "}
            <strong>{docNo}</strong>
          </p>
          <p>
            <span className="text-[var(--muted)]">Date:</span> {date}
          </p>
          {partyName ? (
            <p>
              <span className="text-[var(--muted)]">Party:</span>{" "}
              {partyCode ? `${partyCode} — ` : ""}
              {partyName}
            </p>
          ) : null}
          {warehouseName ? (
            <p>
              <span className="text-[var(--muted)]">Warehouse:</span> {warehouseName}
            </p>
          ) : null}
          {extraMeta?.map((m) => (
            <p key={m.label}>
              <span className="text-[var(--muted)]">{m.label}:</span> {m.value}
            </p>
          ))}
        </div>

        <table className="mt-6 w-full border-collapse text-sm">
          <thead>
            <tr className="border-y border-[var(--border)] text-left text-[11px] uppercase tracking-wide text-[var(--muted)]">
              <th className="py-2">Code</th>
              <th className="py-2">Item</th>
              <th className="py-2 text-right">Qty</th>
              {lines.some((l) => l.rate != null) ? (
                <th className="py-2 text-right">Rate</th>
              ) : null}
              {lines.some((l) => l.amount != null) ? (
                <th className="py-2 text-right">Amount</th>
              ) : null}
            </tr>
          </thead>
          <tbody>
            {lines.map((l, i) => (
              <tr key={`${l.product_code}-${i}`} className="border-b border-[var(--border)]">
                <td className="py-2">{l.product_code}</td>
                <td className="py-2">{l.product_name}</td>
                <td className="py-2 text-right">{l.qty}</td>
                {lines.some((x) => x.rate != null) ? (
                  <td className="py-2 text-right">
                    {l.rate != null ? formatPkr(l.rate) : "—"}
                  </td>
                ) : null}
                {lines.some((x) => x.amount != null) ? (
                  <td className="py-2 text-right">
                    {l.amount != null ? formatPkr(l.amount) : "—"}
                  </td>
                ) : null}
              </tr>
            ))}
          </tbody>
        </table>

        {totals?.length ? (
          <div className="mt-4 ml-auto w-full max-w-xs space-y-1 text-sm">
            {totals.map((t) => (
              <div key={t.label} className="flex justify-between gap-4">
                <span className="text-[var(--muted)]">{t.label}</span>
                <strong>{t.value}</strong>
              </div>
            ))}
          </div>
        ) : null}

        <p className="mt-10 text-xs text-[var(--muted)]">
          Generated by Umar Distribution Software
        </p>
      </div>
    </div>
  );
}
